#### Mandatory configurations ####

# Network to use. Should be one of:
# network: Testnet
# network: Mainnet
# network: Devnet
# network: !Custom
#   node_url: 'url_to_node_endpoint'  # Optional - see below
#   use_default_mainnet_for_mvr: true # Optional, default to true if not present, 
# set this to false for mvr to resolve on testnet. 
#
# Use Custom for production deployments. You must provide the node URL
# in exactly one of these ways:
# 1. Set the `node_url` in this config file
# 2. OR omit `node_url` here and set the NODE_URL environment variable
#
#
# Example:
network: Testnet


# Server mode. The server can either work in Open/permissionless mode that 
# supports all packages, or in Permissioned mode that only supports
# whitelisted packages .
#
# For the Open mode, set the registered key server object ID to be used, e.g.,:
# server_mode: !Open
#   key_server_object_id: '0x0000000000000000000000000000000000000000000000000000000000005ea1'
#
# Example:
server_mode: !Open
  key_server_object_id: '0x00000000000000000000000000000000000000000000000000000000000005ea1

#### Optional advanced configurations ####
#
# The port that the prometheus agent can use to poll for the metrics.
metrics_host_port: 9184
#
# The minimum version of the SDK that is required to use this service.
# sdk_version_requirement: '>=0.4.5'
#
# Update intervals and timeouts for various operations. Example values are shown below.
checkpoint_update_interval: '10s'
rgp_update_interval: '60s'
allowed_staleness: '2m'
session_key_ttl_max: '30m'

# Optional: Metrics push configuration to send metrics to mydata-proxy
# Uncomment and configure to enable pushing metrics to an external endpoint
metrics_push_config:
  bearer_token: "key-server-token-placeholder"
  push_interval_secs: 10
  push_url: "https://mydata-proxy-testnet.up.railway.app/publish/metrics"
