listen-address: 0.0.0.0:8000
metrics-address: 0.0.0.0:9185
histogram-address: 0.0.0.0:8001
label-actions:
  add:
    network: "railway-production"
    host: "mydata-proxy"
remote-write:
  url: "https://mydata-mimir-testnet.up.railway.app/api/v1/push"
  username: ""
  password: ""
  pool_max_idle_per_host: 100
