[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cargo run --bin key-server"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
RUST_LOG = "info"
RUST_BACKTRACE = "1"
NODE_URL = "http://fullnode.testnet.mysocial.network:9000"
NETWORK = "Testnet"
SERVER_MODE = "Open"
KEY_SERVER_OBJECT_ID = "0x0000000000000000000000000000000000000000000000000000000000005ea1"
METRICS_HOST_PORT = "9184"
METRICS_PUSH_URL = "https://mydata-proxy-testnet.up.railway.app/publish/metrics"
METRICS_PUSH_INTERVAL_SECS = "10"
MASTER_KEY = "0x25e578903be963387a68e65f6ac0192536def94cd992805386497b8c27cee4ca"

[[volumes]]
name = "config"
mountPath = "/app/config"

[[services]]
name = "mydata-key-server-2"
source = { repo = "https://github.com/The-Social-Proof-Foundation/mys-mydata", branch = "main" }

[services.variables]
PORT = "8080"
METRICS_PORT = "9184"
