[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cargo run --bin mydata-proxy -- --config=mydata-proxy.yaml --bearer-tokens-path=bearer-tokens.yaml"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
RUST_LOG = "info"
RUST_BACKTRACE = "1"
LISTEN_ADDRESS = "0.0.0.0:8000"
METRICS_ADDRESS = "0.0.0.0:9185"
HISTOGRAM_ADDRESS = "0.0.0.0:8001"
REMOTE_WRITE_URL = "https://mydata-mimir-testnet.up.railway.app/api/v1/push"
REMOTE_WRITE_USERNAME = ""
REMOTE_WRITE_PASSWORD = ""
LABEL_NETWORK = "railway-production"
LABEL_HOST = "mydata-proxy"

[[volumes]]
name = "config"
mountPath = "/app/config"

[[services]]
name = "mydata-proxy"
source = { repo = "https://github.com/The-Social-Proof-Foundation/mys-mydata", branch = "main" }

[services.variables]
PORT = "8000"
METRICS_PORT = "9185"
HISTOGRAM_PORT = "8001"
