name: Move

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MOVE_PACKAGES_PATH: move

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v4
        with:
          fetch-depth: 1

      - name: Install MySocial
        uses: cloudposse-github-actions/install-gh-releases@33b15dbedceb0a3425d72f54a2300202d5c3418d # pin@v1.5.0
        with:
          config: |-
            mystenlabs/mys:
              platform: ubuntu
              arch: x86_64
              extension-matching: true
              tag: testnet-v1.52.1

      - name: Run move tests
        run: |
          for dir in move/*; do
            echo "Running mys move test in $dir"
            mys move test --warnings-are-errors --path $dir
          done

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: MystenLabs/move-formatter-action@v1
        with:
          prettier-plugin-move-version: "latest"
          working-directory: ${{ env.MOVE_PACKAGES_PATH }}
